### PR TITLE
ms teams notification added

### PR DESCRIPTION
**Pull request by TheEhsanSarshar**

### CODE REVIEW

**Comment by TheEhsanSarshar** [comment]
recheck

**Comment by TheEhsanSarshar** [comment]
@AnandChowdhary 
sorry for mentioning!
do you have time to review this?

**Comment by AnandChowdhary** [comment]
Thanks for the PR! The diff is too big so I have trouble reviewing :( You don't have to modify the .js files since those are auto-generated. Can you please edit the branch with only changes to .ts source files? Thanks so much again for the PR!

**Comment by TheEhsanSarshar** [comment]
@AnandChowdhary thanks for your comment. those are build files, if any workflow in the library auto generate them after merging the PR, I can cherry-pick that built commit.

**Comment by AnandChowdhary** [comment]
Hey, yes, we only need to update the .ts files and the .js ones will auto generate via CI :)

**Pull request closed without merging**
