### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by dsogo**
translation readme pt-br

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
This is great, thank you so very much! Do you think you can also translate the README of [upptime/upptime](https://github.com/upptime/upptime), the main repo for this project?

**Comment by dsogo** [comment]
yes

**Comment by AnandChowdhary** [comment]
Can you also please sign the CLA? You can enter the comment "I have read the CLA Document and I hereby sign the CLA" to confirm that you have read it, it is available at https://github.com/koj-co/.github/blob/master/CLA.md.

**Comment by AnandChowdhary** [comment]
I'm closing this because all the markdown is malformed.

**Pull request closed without merging**
