### PR TITLE
:bug: Fix typo in README.md(montor -> monitor)

### PR DESCRIPTION
**Pull request by billchenchina**

### CODE REVIEW

**Comment by billchenchina** [comment]
> **CLA Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Contributor License Agreement](https://github.com/koj-co/.github/blob/master/CLA.md) before we can accept your contribution. You can sign the CLA by adding a comment below using this text:
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by billchenchina** [comment]
recheck

**Comment by AnandChowdhary** [comment]
@billchenchina, you only have to copy and paste the line starting with "I have read..."

**Comment by billchenchina** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
