### PR TITLE
:bug: Upgrade to Node.js v18

### PR DESCRIPTION
**Pull request by zgrossbart**
…ndency requirements.

### CODE REVIEW

**Comment by rastislavcore** [comment]
@AnandChowdhary this will fix the blocker

**Review by floydnoel — APPROVED** [review]
LGTM 🚀

**Comment by Rileyjrjohns** [comment]
Please merge

**Comment by floydnoel** [comment]
@AnandChowdhary is this something you could take a look at? We are seeing constant failed jobs emails from GitHub from https://github.com/upptime/upptime/issues/800

thank you!

**Review by GeekCornerGH — APPROVED** [review]
Just change the title, it's Node.JS 18 not 19 ;)

**Comment by AnandChowdhary** [comment]
Unfortunately this can't be merged because:

```
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@2.3.4 and node@18.16.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
```

We'd tried this before as well, but we need to figure out how to make node-libcurl work with Node v18 first:

CleanShot 2023-06-15 at 09 45 56@2x

**Comment by Rileyjrjohns** [comment]
Don't forget to update all dependencies...

**Comment by Rileyjrjohns** [comment]
Ok let me check that

**Pull request merged**
