### PR TITLE
👷 Use current node-version 20

### PR DESCRIPTION
**Pull request by thomasmerz**
As asked for in https://github.com/upptime/uptime-monitor/pull/239 here's a PR to update `node-version`.

This PR fixes issue https://github.com/upptime/upptime/issues/969

### CODE REVIEW

**Comment by Rileyjrjohns** [comment]
@AnandChowdhary

**Comment by thomasmerz** [comment]
@AnandChowdhary , can you please have a look at this PR and merge, comment or close it? Thank you!

**Comment by mchelen** [comment]
Ok, I think the install and build errors have been resolved here: https://github.com/thomasmerz/uptime-monitor/pull/1

This fixes https://github.com/upptime/upptime/issues/969

**Comment by thomasmerz** [comment]
Build errors are fixed by @mchelen (thanks!) - so @AnandChowdhary this PR is ready for your review.

**Pull request merged**
