### PR TITLE
Add Discord webhook notifications

### PR DESCRIPTION
**Pull request by AndrewLaneX**
Similar to the Slack notifications, you can now get notifications in Discord by [creating a webhook](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks).

### CODE REVIEW

**Comment by AndrewLaneX** [comment]
The CLA link is broken :thinking:

**Comment by AndrewLaneX** [comment]
I found [Contributing Guidelines](https://github.com/upptime/.github/blob/main/CONTRIBUTING.md) [the Code of Conduct](https://github.com/upptime/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by AndrewLaneX** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by AnandChowdhary** [comment]
This is great, thank you so much! I'll merge this later today.

**Review by AnandChowdhary — APPROVED** [review]

**Pull request merged**
